#
# Use nix-emacs-ci for travis CI
# URL: https://github.com/purcell/nix-emacs-ci
#

language: nix

os:
  - linux

env:
  - EMACS_CI=emacs-26-1
  - EMACS_CI=emacs-26-2
  - EMACS_CI=emacs-26-3

install:
  # The default "emacs" executable on the $PATH will now be the version named by $EMACS_CI
  - bash <(curl https://raw.githubusercontent.com/purcell/nix-emacs-ci/master/travis-install)
  # enforce the stable channel version
  - nix-channel --add https://nixos.org/channels/nixos-20.03 nixpkgs-stable
  - nix-channel --update nixpkgs-stable
  - nix-channel --list
  - nix-env -iA nixpkgs-stable.cask

script:
  - make install test
